# roles/rancher_deploy/tasks/main.yml
---
  - name: "create directory ~/.rancher"
    file:
      path: "~/.rancher"
      state: directory
    when:
      - rancher.deploy

  - name: generate "~/.rancher/rancher.config.yaml"
    template:
      src: templates/rancher.config.yml.j2
      dest: "~/.rancher/rancher.config.yaml"
      owner: nutanix
      group: nutanix
      mode: '0600'
    when:
      - rancher.deploy

  - name: Add rancher Helm repository
    kubernetes.core.helm_repository:
      name: "{{ rancher.repo }}"
      repo_url: "https://releases.rancher.com/server-charts/latest"
    when:
      - rancher.deploy

  - name: Ensure namespace exists
    kubernetes.core.k8s:
      name: "{{ rancher.namespace }}"
      api_version: v1
      kind: Namespace
      state: present
      wait: yes
      wait_timeout: 5m
    when:
      - rancher.deploy

  - name: add Jetstack Helm repository
    kubernetes.core.helm_repository:
      name: jetstack
      repo_url: "https://charts.jetstack.io"
    when:
      - rancher.deploy

  - name: install the cert-manager Helm chart
    kubernetes.core.helm:
      name: "cert-manager"
      kubeconfig: "~/kube_config_rke-cluster.yml"
      chart_ref: jetstack/cert-manager
      namespace: "cert-manager"
      create_namespace: yes
      update_repo_cache: yes
      wait: yes
      wait_timeout: 5m
      values:
        installCRDs: true
    when:
      - rancher.deploy

  - name: install rancher
    kubernetes.core.helm:
      name: "rancher"
      kubeconfig: "~/kube_config_rke-cluster.yml"
      chart_ref: rancher-stable/rancher
      namespace: cattle-system
      release_state: present
      update_repo_cache: yes
      values: "{{ lookup('template', 'rancher.config.yml.j2') | from_yaml }}"
      wait: yes
      wait_timeout: 15m
    when:
      - rancher.deploy
