# ansible-playbook -i inventory/inventory.ini -vv playbook-deploy-ntnx-csi-helm.yml
---
  - name: "Deploy Nutanix CSI Driver"
    hosts: admin_vm
    collections:
      - kubernetes.core
    roles:
      - helm_ntnx_csi_driver
