---
  - name: "Common Setup for all servers"
    hosts: all
    roles:
      - setup_common

  - name: "Setup admin server"
    hosts: admin_vm
    roles:
      - setup_admin_vm

  - name: "Setup RKE servers"
    hosts: controlplane_vms:etcd_vms:worker_vms
    roles:
      - setup_rke_vms

  - name: "Deploy RKE"
    hosts: admin_vm
    roles:
      - rke_generate_config
      - rke_deploy
      # - ntnx_csi_driver_deploy
