---
# file: playbook_image_nodes.yml
# ansible-playbook site.yml -i inventory -e cluster_name="test_cluster" -t download
# ansible-playbook site.yml -i inventory -c paramiko -e cluster_name="test_cluster" -t download
  - name: "Deploy RKE"
    hosts: localhost
    tasks:
    - include_role: {  name: deploy_rke }
