---
  - name: "Common Setup for all servers"
    hosts: all
    roles:
      - setup_common

  - name: "Setup admin server"
    hosts: admin_vm
    roles:
      - setup_admin_vm

  - name: "Setup RKE servers"
    hosts: controlplane:etcd:workers
    roles:
      - setup_rke_vms

  - name: "Deploy/Scale RKE"
    hosts: admin_vm
    roles:
      - deploy_rke
