---
  - name: "Common Setup for all servers"
    hosts: etcd_vms
    roles:
      - setup_common

  - name: "Setup admin server"
    hosts: admin_vm
    roles:
      - setup_admin_vm

  - name: "Setup RKE servers"
    hosts: etcd_vms
    roles:
      - setup_rke_vms

  - name: "Generate RKE Configuration"
    hosts: admin_vm
    roles:
      - rke_generate_config

  - name: "Scale RKE ETCD"
    hosts: admin_vm
    roles:
      - rke_scale_etcd
