# ansible-playbook -i inventory/inventory.ini -vv playbook-scale-rke-worker.yml
---
  - name: "Common Setup for all servers"
    hosts: worker_vms
    roles:
      - setup_common

  - name: "Setup admin server"
    hosts: admin_vm
    roles:
      - setup_admin_vm

  - name: "Setup RKE servers"
    hosts: worker_vms
    roles:
      - setup_rke_vms

  - name: "Generate RKE Configuration"
    hosts: admin_vm
    roles:
      - rke_generate_config

  - name: "Scale RKE Workers"
    hosts: admin_vm
    roles:
      - rke_scale_worker
