# roles/rke_generate_config/defaults/main.yml
ntnx_csi_conf_dir: "~/.ntnx-csi"

# storage class confif
ntnx_pe_ip: ""
ntnx_pe_dataservice_ip: ""
ntnx_pe_username: "admin"
ntnx_pe_password: "nutanix/4u"
auth_string: "{{ nutanix_pe_ip_address }}:{{ nutanix_pe_username }}:{{ nutanix_pe_password }}"
defaultStorageClass: "none"  # none | volumes | files | files-dynamic

# volumes sc config
volumesClass: false
volumesClassName: "nutanix-volumes"
volumesStorageContainer: ""
volumesFsType: "xfs"  # ext4 | xfs
volumesReclaimPolicy: "Delete"  # Delete | Retain
volumesWhitelistIPAddr: ""
volumesWhitelistIPMode: "DISABLED"  # ENABLED | DISABLED
volunesChapAuth: "DISABLED"  # ENABLED | DISABLED
volumesFlashMode: "DISABLED"  # ENABLED | DISABLED

# files
filesClass: false
filesClassName: "nutanix-files"
filesNfsServer: ""
filesNfsPath: ""
filesReclaimPolicy: "Delete"  # Delete | Retain

# dynamic files
filesDynamicClass: false
filesDynamicClassName: "nutanix-files-dynamic"
filesNfsServerName: ""
filesReclaimPolicy: "Delete"  # Delete | Retain

# rke
port: 22
user: nutanix
docker_socket: /var/run/docker.sock
ingress: nginx
# servers:
#   controlplane:
#     - x.x.x.x
#     - x.x.x.y
#   workers:
#     - x.x.z.x
#     - x.x.z.y
ignore_docker_version: true
enable_cri_dockerd: false
ssh_key_path: ~/.ssh/id_rsa
ssh_agent_auth: false
# private_registries:
#   - url: registry.com
#     user: Username
#     password: password
#     is_default: true
# bastion_host:
#   address: x.x.x.x
#   user: ubuntu
#   port: 22
#   ssh_key_path: /home/user/.ssh/bastion_rsa
# cluster_name: "mycluster"
kubernetes_version: "v1.17.17-rancher1-1"
# system_images:
#     kubernetes: rancher/hyperkube:v1.10.3-rancher2
#     etcd: rancher/coreos-etcd:v3.1.12
#     alpine: rancher/rke-tools:v0.1.9
#     nginx_proxy: rancher/rke-tools:v0.1.9
#     cert_downloader: rancher/rke-tools:v0.1.9
#     kubernetes_services_sidecar: rancher/rke-tools:v0.1.9
#     kubedns: rancher/k8s-dns-kube-dns-amd64:1.14.8
#     dnsmasq: rancher/k8s-dns-dnsmasq-nanny-amd64:1.14.8
#     kubedns_sidecar: rancher/k8s-dns-sidecar-amd64:1.14.8
#     kubedns_autoscaler: rancher/cluster-proportional-autoscaler-amd64:1.0.0
#     pod_infra_container: rancher/pause-amd64:3.1
# authentication:
#     strategy: x509
#     sans:
#       - "10.18.160.10"
#       - "my-loadbalancer-1234567890.us-west-2.elb.amazonaws.com"
authorization:
  mode:  none # none or rbac
# cloud_provider:
#     name: aws
addon_job_timeout: 30
network_plugin: canal # canal, calico, flannel, weave, or none
dns_provider: coredns # none, coredns or kube-dns
upstream_dns_servers:
  - 1.1.1.1
  - 8.8.4.4
ingress_provider: nginx # none, nginx
addons_include:
  - "{{ ntnx_csi_conf_dir }}/ntnx-csi-rbac.yaml"
  - "{{ ntnx_csi_conf_dir }}/ntnx-csi-node.yaml"
  - "{{ ntnx_csi_conf_dir }}/ntnx-csi-provisioner.yaml"
  - "{{ ntnx_csi_conf_dir }}/csi-driver.yaml"
  - "{{ ntnx_csi_conf_dir }}/ntnx-csi-secret.yaml"
