# roles/rke_scale_worker/tasks/run_rke_scale_worker.yml
---
  - name: invoke rke to scale worker nodes
    shell: /usr/bin/rke up --update-only --config ~/rke-cluster.yml
    args:
      executable: /bin/bash
