# roles/host_prep/tasks/config_iptable_rules.yml
---
  - name: Allow related and established connections
    iptables:
      chain: INPUT
      ctstate: ESTABLISHED,RELATED
      jump: ACCEPT
    when:
      - "'controlplane' in group_names"
      - "'workers' in group_names"
    become: yes

  - name: Allow new incoming SYN packets on TCP port 22 (SSH).
    iptables:
      chain: INPUT
      protocol: tcp
      destination_port: "22"
      ctstate: NEW
      syn: match
      jump: ACCEPT
      comment: Accept new SSH connections.
    when:
      - "'controlplane' in group_names"
      - "'workers' in group_names"
    become: yes

  - name: IPtables allow TCP/80 inbound from anywhere
    iptables:
      chain: INPUT
      protocol: tcp
      source: 0.0.0.0/0
      destination_port: "80"
      jump: ACCEPT
    when:
      - "'controlplane' in group_names"
      - "'workers' in group_names"
    become: yes

  - name: IPtables allow TCP/443 inbound from anywhere
    iptables:
      chain: INPUT
      protocol: tcp
      source: 0.0.0.0/0
      destination_port: "443"
      jump: ACCEPT
    when:
      - "'controlplane' in group_names"
      - "'workers' in group_names"
    become: yes














  - name: RKE Control Plane TCP/80
    iptables:
      chain: INPUT
      protocol: tcp
      destination_port: "80"
      jump: ACCEPT
    when:
        - "'controlplane' in group_names"
    loop: "{{ groups['controlplane'] }}"
    become: yes



  - name: RKE Control Plane VM IPtables Inbound Rules
    iptables:
      chain: INPUT
      protocol: "{{ item.protocol }}"
      destination_port: "{{ item.port }}"
      jump: ACCEPT
    when:
      - "'controlplane' in group_names"
    loop: "{{ control_plane_fw_inbound }}"
    become: yes

  - name: RKE Worker VM IPtables Inbound Rules
    iptables:
      chain: INPUT
      protocol: "{{ item.protocol }}"
      destination_port: "{{ item.port }}"
      jump: ACCEPT
    when:
      - "'workers' in group_names"
    loop: "{{ worker_fw_inbound }}"
    become: yes
