# roles/host_prep/tasks/iptables.yml
---
  - name: Allow related and established connections
    iptables:
      chain: INPUT
      ctstate: ESTABLISHED,RELATED
      jump: ACCEPT
    become: yes

  - name: Allow new incoming SYN packets on TCP port 22 (SSH).
    iptables:
      chain: INPUT
      protocol: tcp
      destination_port: "22"
      ctstate: NEW
      syn: match
      jump: ACCEPT
      comment: Accept new SSH connections.
    become: yes

  - name: RKE Control Plane VM IPtables Inbound Rules
    iptables:
      chain: INPUT
      protocol: "{{ item.protocol }}"
      destination_port: "{{ item.port }}"
      ctstate: NEW
      jump: ACCEPT
      when: "'controlplane' in group_names"
    loop: "{{ control_plane_fw_inbound }}"
    become: yes

  - name: RKE Worker VM IPtables Inbound Rules
    iptables:
      chain: INPUT
      protocol: "{{ item.protocol }}"
      destination_port: "{{ item.port }}"
      ctstate: NEW
      jump: ACCEPT
      when: "'workers' in group_names"
    loop: "{{ worker_fw_inbound }}"
    become: yes
