# roles/host_prep/tasks/config_firewalld.yml
---
  - name: open inbound worker firewall services
    become: yes
    firewalld:
      service: "{{ item }}"
      permanent: true
      state: enabled
    with_items: "{{ rancher_rke_fw_worker_svc.inbound }}"

  - name: open inbound worker firewall ports
    become: yes
    firewalld:
      port: "{{ item }}"
      permanent: true
      state: enabled
    with_items: "{{ rancher_rke_fw_worker_ports.inbound }}"
