# roles/setup_rke_vms/tasks/config_firewalld_etcd.yml
---
  - name: open inbound etcd firewall services
    become: yes
    firewalld:
      service: "{{ item }}"
      permanent: true
      state: enabled
    with_items: "{{ rancher_rke_fw_etcd_svc.inbound }}"

  - name: open inbound etcd firewall ports
    become: yes
    firewalld:
      port: "{{ item }}"
      permanent: true
      state: enabled
    with_items: "{{ rancher_rke_fw_etcd_ports.inbound }}"
