# roles/setup_rke_vms/tasks/config_docker.yml
---
  - name: /etc/docker/daemon.json
    become: yes
    template:
      src: templates/docker_daemon.json.j2
      dest: /etc/docker/daemon.json
      owner: root
      group: root
      mode: '0644'
    notify: "restart docker"
