# roles/host_prep/tasks/config_firewalld.yml
---
  - name: open inbound control plane firewall services
    become: yes
    firewalld:
      service: "{{ item }}"
      permanent: true
      state: enabled
    loop:
      - {{ rancher_rke_fw_controlplane_svc.inbound }}
      - {{ rancher_rke_fw_etcd_svc.inbound }}
    when:
      - "'controlplane' in group_names"

  - name: open inbound control plane firewall ports
    become: yes
    firewalld:
      port: "{{ item }}"
      permanent: true
      state: enabled
    loop:
      - {{ rancher_rke_fw_etcd_ports.inbound }}
    when:
      - "'controlplane' in group_names"

  - name: open inbound etcd firewall services
    become: yes
    firewalld:
      service: "{{ item }}"
      permanent: true
      state: enabled
    loop:
      - {{ rancher_rke_fw_etcd_svc.inbound }}
    when:
      - "'etcd' in group_names"

  - name: open inbound etcd firewall ports
    become: yes
    firewalld:
      port: "{{ item }}"
      permanent: true
      state: enabled
    loop:
      - {{ rancher_rke_fw_etcd_ports.inbound }}
    when:
      - "'etcd' in group_names"

  - name: open inbound worker firewall services
    become: yes
    firewalld:
      service: "{{ item }}"
      permanent: true
      state: enabled
    loop:
      - {{ rancher_rke_fw_worker_svc.inbound }}
    when:
      - "'workers' in group_names"

  - name: open inbound worker firewall ports
    become: yes
    firewalld:
      port: "{{ item }}"
      permanent: true
      state: enabled
    loop:
      - {{ rancher_rke_fw_worker_ports.inbound }}
    when:
      - "'workers' in group_names"
