# roles/setup_rke_vms/tasks/config_firewalld_controlplane.yml
---
  - name: open inbound control plane firewall services
    become: yes
    firewalld:
      service: "{{ item }}"
      permanent: true
      state: enabled
    with_items: "{{ rancher_rke_fw_controlplane_svc.inbound }}"

  - name: open inbound control plane firewall ports
    become: yes
    firewalld:
      port: "{{ item }}"
      permanent: true
      state: enabled
    with_items: "{{ rancher_rke_fw_controlplane_ports.inbound }}"
