# roles/setup_rke_vms/tasks/disable_firewalld.yml
---
  - name: stop firewalld
    become: yes
    service:
      name: firewalld
      state: stopped

  - name: disable firewalld
    become: yes
    service:
      name: firewalld
      enabled: no
