# roles/setup_rke_vms/tasks/disable_swap.yml
---
  - name: Disable SWAP since kubernetes can't work with swap enabled (1/2)
    become: yes
    shell: swapoff -a

  - name: Disable SWAP in fstab since kubernetes can't work with swap enabled (2/2)
    become: yes
    replace:
      path: /etc/fstab
      regexp: '^([^#].*?\sswap\s+.*)$'
      replace: '# \1'
