# roles/host_prep/tasks/install_kubectl.yml
---
  - name: add docker-ce yum repo
    yum_repository:
      name: docker-ce-stable
      description: Docker CE Stable Repo
      baseurl: https://download.docker.com/linux/centos/7/$basearch/stable
      gpgkey: https://download.docker.com/linux/centos/gpg
      gpgcheck: yes
      enabled: yes
    become: yes

  - name: install the latest version of docker-ce
    become: yes
    package:
      name:
        - "docker-ce"
        - "docker-ce-cli"
        - "containerd.io"
      state: present
    when: ansible_pkg_mgr in ('apt', 'yum', 'dnf', 'zypper')

  - name: Enable docker service
    service:
      name: docker
      enabled: yes
    become: yes

  - name: Start docker service
    service:
      name: docker
      state: started
    become: yes

  - name: Add the user 'nutanix' to the 'docker' group
    user:
      name: nutanix
      group: docker
      append: yes
    become: yes

  - name: Get docker version
    shell: docker version
    become: yes
