# roles/setup_rke_vms/tasks/install_csi_packages.yml
---
  - name: install iscsi-initiator-utils & nfs-utils
    become: yes
    package:
      name:
        - "iscsi-initiator-utils"
        - "nfs-utils"
      state: present
    when: ansible_pkg_mgr in ('apt', 'yum', 'dnf', 'zypper')

  - name: Enable iscsi service
    service:
      name: iscsid
      enabled: yes
    become: yes

  - name: Start iscsi service
    service:
      name: iscsid
      state: started
    become: yes
