# roles/deploy_rke/tasks/install_chrony.yml
---
  - name: Install chrony
    become: yes
    package:
      name:
        - "chrony"
      state: present
    when: ansible_pkg_mgr in ('apt', 'yum', 'dnf', 'zypper')

  - name: Enable chrony
    service:
      name: chronyd
      enabled: yes
    become: yes

  - name: Start chrony
    service:
      name: chronyd
      state: started
    become: yes
