# roles/setup_rke_vms/tasks/main.yml
---
  - name: "install chrony"
    include_tasks: install_chrony.yml

  # - name: "configure controlplane firewall"
  #   include_tasks: config_firewalld_controlplane.yml
  #   when: "'controlplane_vms' in group_names"
  #
  # - name: "configure etcd firewall"
  #   include_tasks: config_firewalld_etcd.yml
  #   when: "'etcd_vms' in group_names"
  #
  # - name: "configure worker firewall"
  #   include_tasks: config_firewalld_worker.yml
  #   when: "'worker_vms' in group_names"

  - name: "remove any old docker versions"
    include_tasks: remove_old_docker_versions.yml

  - name: "install docker"
    include_tasks: install_docker.yml

  - name: "configure docker"
    include_tasks: config_docker.yml

  - name: "disable swap"
    include_tasks: disable_swap.yml

  - name: "configure sysctl"
    include_tasks: config_sysctl.yml

  - name: "configure kernel modules"
    include_tasks: config_kernel_modules.yml

  - name: "install packages for nutanix csi driver"
    include_tasks: install_csi_packages.yml
