# roles/rke_generate_config/tasks/main.yml
---
  - name: "include {{ network_plugin }} network defaults"
    include_vars: "network-{{ network_plugin }}.yml"
    tags: always

  - name: "generate cluster configuration file"
    include_tasks: create_rke_cluster_config.yml
    tags: always
