# roles/helm_ntnx_csi_driver/tasks/install_csi_helm.yml
---
  - name: "create directory {{ ntnxCsiDir }}"
    file:
      path: "{{ ntnxCsiDir }}"
      state: directory

  - name: "generate {{ ntnxCsiDir }}/ntnx-csi-secret.yaml"
    template:
      src: templates/ntnx-csi-secret.yml.j2
      dest: "{{ ntnxCsiDir }}/ntnx-csi-secret.yaml"
      owner: nutanix
      group: nutanix
      mode: '0600'

  - name: "create secret {{ secretName }} in namespace {{ ntnxCsiNamespace }}"
    kubernetes.core.k8s:
      state: present
      kubeconfig: "~/kube_config_rke-cluster.yml"
      src: "{{ ntnxCsiDir }}/ntnx-csi-secret.yaml"

  - name: Add nutanix csi chart repo
    kubernetes.core.helm_repository:
      name: nutanix
      repo_url: "https://nutanix.github.io/helm/"

  - name: generate "{{ ntnxCsiDir }}/ntnx-csi-snapshots-helm-values.yaml"
    template:
      src: templates/ntnx-csi-snapshots-helm-values.yml.j2
      dest: "{{ ntnxCsiDir }}/ntnx-csi-snapshots-helm-values.yaml"
      owner: nutanix
      group: nutanix
      mode: '0600'

  - name: helm install nutanix csi snapshot driver
    kubernetes.core.helm:
      name: nutanix-csi
      kubeconfig: ~/kube_config_rke-cluster.yml
      chart_ref: nutanix/nutanix-csi-storage
      release_namespace: "{{ ntnxCsiNamespace }}"
      release_state: present
      update_repo_cache: yes
      values_files: "{{ lookup('template', 'ntnx-csi-snapshots-helm-values.yml.j2') | from_yaml }}"

  - name: generate "{{ ntnxCsiDir }}/csi-helm-values.yaml"
    template:
      src: templates/ntnx-csi-helm-values.yml.j2
      dest: "{{ ntnxCsiDir }}/helm-values.yaml"
      owner: nutanix
      group: nutanix
      mode: '0600'

  - name: helm install nutanix csi driver
    kubernetes.core.helm:
      name: nutanix-csi
      kubeconfig: ~/kube_config_rke-cluster.yml
      chart_ref: nutanix/nutanix-csi-storage
      release_namespace: "{{ ntnxCsiNamespace }}"
      release_state: present
      update_repo_cache: yes
      values_files: "{{ lookup('template', 'ntnx-csi-helm-values.yml.j2') | from_yaml }}"
