# roles/ntnx_csi_driver_deploy/tasks/install_csi_driver.yml
---
  - name: apply ntnx-csi-rbac.yaml
    shell: "/usr/bin/kubectl apply -f {{ ntnxCsiDir }}/ntnx-csi-rbac.yaml"
    args:
      executable: /bin/bash

  # - name: apply ntnx-csi-rbac.yaml
  #   kubernetes.core.k8s:
  #     state: present
  #     kubeconfig: "{{ kubeconfig }}"
  #     src: "{{ ntnxCsiDir }}/ntnx-csi-rbac.yaml"

  - name: apply ntnx-csi-node.yaml
    shell: "/usr/bin/kubectl apply -f {{ ntnxCsiDir }}/ntnx-csi-node.yaml"
    args:
      executable: /bin/bash

  # - name: apply ntnx-csi-node.yaml
  #   kubernetes.core.k8s:
  #     state: present
  #     kubeconfig: "{{ kubeconfig }}"
  #     src: "{{ ntnxCsiDir }}/ntnx-csi-node.yaml"

  - name: apply ntnx-csi-provisioner.yaml
    shell: "/usr/bin/kubectl apply -f {{ ntnxCsiDir }}/ntnx-csi-provisioner.yaml"
    args:
      executable: /bin/bash

  # - name: apply ntnx-csi-provisioner.yaml
  #   kubernetes.core.k8s:
  #     state: present
  #     kubeconfig: "{{ kubeconfig }}"
  #     src: "{{ ntnxCsiDir }}/ntnx-csi-provisioner.yaml"

  - name: apply csi-driver.yaml
    shell: "/usr/bin/kubectl apply -f {{ ntnxCsiDir }}/csi-driver.yaml"
    args:
      executable: /bin/bash

  # - name: apply csi-driver.yaml
  #   kubernetes.core.k8s:
  #     state: present
  #     kubeconfig: "{{ kubeconfig }}"
  #     src: "{{ ntnxCsiDir }}/csi-driver.yaml"

  - name: apply ntnx-csi-secret.yaml
    shell: "/usr/bin/kubectl apply -f {{ ntnxCsiDir }}/ntnx-csi-secret.yaml"
    args:
      executable: /bin/bash

  # - name: ntnx-csi-secret.yaml
  #   kubernetes.core.k8s:
  #     state: present
  #     kubeconfig: "{{ kubeconfig }}"
  #     src: "{{ ntnxCsiDir }}/ntnx-csi-secret.yaml"

  - name: apply ntnx-csi-sc-volumes.yaml
    shell: "/usr/bin/kubectl apply -f {{ ntnxCsiDir }}/ntnx-csi-sc-volumes.yaml"
    args:
      executable: /bin/bash
    when: volumesClass

  # - name: ntnx-csi-sc-volumes.yaml
  #   kubernetes.core.k8s:
  #     state: present
  #     kubeconfig: "{{ kubeconfig }}"
  #     src: "{{ ntnxCsiDir }}/ntnx-csi-sc-volumes.yaml"
  #   when: volumesClass

  - name: apply ntnx-csi-sc-files.yaml
    shell: "/usr/bin/kubectl apply -f {{ ntnxCsiDir }}/ntnx-csi-sc-files.yaml"
    args:
      executable: /bin/bash
    when: filesClass

  # - name: ntnx-csi-sc-files.yaml
  #   kubernetes.core.k8s:
  #     state: present
  #     kubeconfig: "{{ kubeconfig }}"
  #     src: "{{ ntnxCsiDir }}/ntnx-csi-sc-files.yaml"
  #   when: filesClass

  - name: apply ntnx-csi-sc-files-dynamic.yaml
    shell: "/usr/bin/kubectl apply -f {{ ntnxCsiDir }}/ntnx-csi-sc-files-dynamic.yaml"
    args:
      executable: /bin/bash
    when: filesDynamicClass

  # - name: ntnx-csi-sc-files-dynamic.yaml
  #   kubernetes.core.k8s:
  #     state: present
  #     kubeconfig: "{{ kubeconfig }}"
  #     src: "{{ ntnxCsiDir }}/ntnx-csi-sc-files-dynamic.yaml"
  #   when: filesDynamicClass
