# roles/ntnx_csi_driver_deploy/tasks/main.yml
---
  - name: ntnx-csi-rbac.yaml
    kubernetes.core.k8s:
      state: present
      kubeconfig: "{{ kubeconfig }}"
      src: "{{ lookup('template', 'ntnx-csi-rbac.yaml') }}"

  - name: ntnx-csi-node.yaml
    kubernetes.core.k8s:
      state: present
      kubeconfig: "{{ kubeconfig }}"
      src: "{{ lookup('template', 'ntnx-csi-node.yaml') }}"

  - name: ntnx-csi-provisioner.yaml
    kubernetes.core.k8s:
      state: present
      kubeconfig: "{{ kubeconfig }}"
      src: "{{ lookup('template', 'ntnx-csi-provisioner.yaml') }}"

  - name: csi-driver.yaml
    kubernetes.core.k8s:
      state: present
      kubeconfig: "{{ kubeconfig }}"
      src: "{{ lookup('template', 'csi-driver.yaml') }}"

  - name: generate b64 encoded string for secret
    set_fact:
      auth_string_b64: "{{ auth_string | b64encode}}"

  - name: ntnx-csi-secret.yaml
    kubernetes.core.k8s:
      state: present
      kubeconfig: "{{ kubeconfig }}"
      src: "{{ lookup('template', 'ntnx-csi-secret.yaml') }}"

  - name: ntnx-csi-sc-volumes.yaml
    kubernetes.core.k8s:
      state: present
      kubeconfig: "{{ kubeconfig }}"
      src: "{{ lookup('template', 'ntnx-csi-sc-volumes.yaml') }}"
    when: volumesClass

  - name: ntnx-csi-sc-files.yaml
    kubernetes.core.k8s:
      state: present
      kubeconfig: "{{ kubeconfig }}"
      src: "{{ lookup('template', 'ntnx-csi-sc-files.yaml') }}"
    when: filesClass

  - name: ntnx-csi-sc-files-dynamic.yaml
    kubernetes.core.k8s:
      state: present
      kubeconfig: "{{ kubeconfig }}"
      src: "{{ lookup('template', 'ntnx-csi-sc-files-dynamic.yaml') }}"
    when: filesDynamicClass
