# roles/ntnx_csi_driver_deploy/tasks/main.yml
---
  - name: "generate csi configuration files"
    include_tasks: generate_config.yml
    tags: always

  - name: "apply csi configuration files"
    include_tasks: install_csi_driver.yml
    tags: always
