# roles/host_prep/tasks/install_helm.yml
---
  - name: install unarchive module dependencies (apt, yum, dnf, zypper)
    package:
      name:
        - tar
        - unzip
        - gzip
      state: present
    when: ansible_pkg_mgr in ('apt', 'yum', 'dnf', 'zypper')
    become: yes

  - name: download helm
    get_url:
      url: "{{ helm_url }}"
      checksum: "sha256:{{ helm_checksum }}"
      dest: "helm_download_dir/helm.tar.gz"
    become: yes

  - name: create helm directory
    file:
      path: "{{ helm_install_dir }}"
      state: directory
    become: yes

  - name: install helm
    unarchive:
      src: /tmp/helm.tar.gz
      remote_src: yes
      dest: "{{ helm_install_dir }}/helm"
      extra_opts:
        - "--strip-components=1"
      owner: root
      group: root
      mode: 'o-w'
    become: yes
    creates: '{{ helm_install_dir }}/helm'

  - name: create helm link
    file:
      src: "{{ helm_install_dir }}/helm"
      dest: "/usr/local/bin/helm"
      state: link
      owner: root
      group: root
      mode: 0755
    become: yes

  - name: install or upgrade tiller
    shell: "/usr/bin/helm init --upgrade"
    become: yes
