# roles/host_prep/tasks/install_helm.yml
---
  - name: download helm
    get_url:
      url: "{{ helm_url }}"
      dest: /tmp/helm.tar.gz
    become: yes

  - name: install helm
    unarchive:
      src: /tmp/helm.tar.gz
      dest: /usr/bin
      owner: root
      group: root
      mode: 0755
      remote_src: yes
    become: yes

  - name: install or upgrade tiller
    shell: "/usr/bin/helm init --upgrade"
    become: yes
