# roles/deploy_rke/tasks/get_rke.yml
---
  - name: Download Rancher RKE
    get_url:
      url: "{{ rancher_rke_download }}"
      dest: /usr/bin/rke
      owner: "root"
      group: "root"
      mode: 0755
    become: yes
    tags:
      - always
