# roles/setup_common/tasks/config_sshd.yml
---
  - name: enable allowtcpforwarding for ssh
    lineinfile:
      path: "/etc/ssh/sshd_config"
      regex: ^(# *)?AllowTcpForwarding
      line: AllowTcpForwarding yes
    notify: "restart sshd"
    become: yes
