# roles/setup_common/tasks/config_firewalld.yml
---
  - name: install firewalld
    yum:
      name: "firewalld"
      state: latest
    become: yes

  - name: enable firewalld
    service:
      name: firewalld
      enabled: yes
    become: yes

  - name: start firewalld
    service:
      name: firewalld
      state: started
    become: yes
