# roles/setup_common/tasks/main.yml
---
  - name: "configure selinux"
    include_tasks: config_selinux.yml

  - name: "configure firewalld"
    include_tasks: config_firewalld.yml

  - name: "configure sshd"
    include_tasks: config_sshd.yml
