# roles/setup_common/tasks/main.yml
---
  - name: "configure selinux"
    include_tasks: config_selinux.yml

  - name: "configure sshd"
    include_tasks: config_sshd.yml

  - name: "disable firewalld"
    include_tasks: disable_firewalld.yml

  - name: "install iptables"
    include_tasks: install_iptables.yml

  # - name: "install firewalld"
  #   include_tasks: install_firewalld.yml

  # - name: "configure firewalld"
  #   include_tasks: config_firewalld.yml
